{% set name = "pyrtcm" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyrtcm-{{ version }}.tar.gz
  sha256: b8567ac8db123772907872db602362363c7b5e83a78c5b89a971a928a2b75f67

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=66.0.0
    - wheel
    - pip
  run:
    - python >=3.8

test:
  imports:
    - pyrtcm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/semuconsulting/pyrtcm
  description: Python library for parsing RTCM3 protocol messages.
  summary: RTCM3 protocol parser
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://www.semuconsulting.com/pyrtcm/
  dev_url: https://github.com/semuconsulting/pyrtcm

extra:
  recipe-maintainers:
    - semuadmin
