{% set name = "pyrtcm" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyrtcm-{{ version }}.tar.gz
  sha256: 0704b98ded95cb55383e989a58907f2ac1b1eb5256bd6b5a01ec65fa90abe9f6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=66.0.0
    - wheel
    - pip
  run:
    - python >=3.9

test:
  imports:
    - pyrtcm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/semuconsulting/pyrtcm
  description: Python library for parsing RTCM3 protocol messages.
  summary: RTCM3 protocol parser
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://www.semuconsulting.com/pyrtcm/
  dev_url: https://github.com/semuconsulting/pyrtcm

extra:
  recipe-maintainers:
    - semuadmin
